Vectorization

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr**2) # it is only bcoz of vectorization
print(arr+10)


[ 1  4  9 16 25]
[11 12 13 14 15]


Broadcasting
- NumPy broadcasting is a powerful feature that allows operations on arrays of different shapes by automatically expanding the smaller array to match the larger one.
- When operating on two arrays, NumPy compares their shapes element-wise. It starts with the
trailing (i.e. rightmost) dimension and its way left. Two dimensions are compatible when
    - they are equal, or
    - one of them is 1.
- One of most popular usecase of broadcasting is Normalization.

In [7]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr + arr2)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


Normalization

In [ ]:
# to normalize an arr -> (arr-mean)/std dev. -> this is called std norma.
# std dev -> sqrt of ((sum of square of ele-mean)/no. of ele)

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std = np.std(arr)

print(mean, std)

normal_Arr = (arr-mean)/std

print(normal_Arr)

2.5 1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
