- MultiDimensional arrays: have dimensions > 1.
- 1D -> axis 0 
- 2D -> axis 0 (rows)(works vertically) & axis 1 (columns)(works horizontally)
- 3D -> axis 0 (layers/depth), axis 1 (rows) & axis 2 (columns)



In [6]:
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

print("sum:", np.sum(arr2d))

sum_of_columns = np.sum(arr2d, axis = 0) 
# why axis 0 bcoz we want sum of all 0 idx in rows
print("sum of cols: ", sum_of_columns) 

sum_of_rows = np.sum(arr2d, axis = 1) 
# why axis 1 bcoz we want sum of all 0 idx in cols
print("sum of rows: ", sum_of_rows) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum: 45
sum of cols:  [12 15 18]
sum of rows:  [ 6 15 24]


In [7]:
# slicing

print(arr2d[0:2, 1:2])

[[2]
 [5]]


3D Array

In [ ]:
arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d, arr3d.shape)

#indexing
print(arr3d[0,1,1]) #[axis0(layer), axis1(row), axis2(col)]

# slicing
print(arr3d[:, 0:1, 0:]) # accessing rows
print(arr3d[:, :, 0:1]) # accessing cols



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[[1 2]]

 [[7 8]]]
[[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]]
